# Generated by Django 2.1.2 on 2020-05-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200524_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
        migrations.AddField(
            model_name='option',
            name='uuid',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='order',
            name='customization',
            field=models.CharField(default='', max_length=250),
        ),
    ]
