# Generated by Django 2.1.2 on 2020-05-24 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200524_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='option',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.Menu'),
        ),
    ]
