# Generated by Django 2.1.2 on 2020-05-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200524_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.Option'),
        ),
    ]
