# Generated by Django 2.1.2 on 2020-05-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200524_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='uuid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='option',
            name='uuid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
